# 속도 비교

In [3]:
print(10)

10


In [5]:
a=10
print(a)

10


In [7]:
a # jupyter 에서는 마지막에선 변수명만 써도 출력이 가능하다. 

10

In [8]:
import numpy as np
import datetime
import time

In [15]:
# list 의 작업시간
li=range(1,1000000)

# 현재 시간 저장
start_time=datetime.datetime.now()


# 모든 요소에 10을 곱해서 list 를 수정
for i in li:
    i=i*10
    
# 현재 시간 저장
end_time=datetime.datetime.now()

print("수행시간 : ", end_time-start_time)

수행시간 :  0:00:00.084485


In [17]:
ar=np.arange(1,1000000)
s=datetime.datetime.now()
ar=ar*10
e=datetime.datetime.now()
print("수행시간 : ",e-s)

수행시간 :  0:00:00.002880


###  배열 정보 확인

In [21]:
ar=np.array([1,2,3])
print(type(ar)) # ar의 자료형
print((ar.dtype)) #ar 에 저장된 요소의 자료형
print(ar.ndim) # 1차원 배열
print(ar.shape) # 3개의 행으로 구성. ( 행과 열의 개수를 알려준다. )

<class 'numpy.ndarray'>
int64
1
(3,)


In [24]:
ar=np.array([[1,2,3],[4,5,6]])
print(ar.ndim) # 1차원 배열
print(ar.shape) # 3개의 행으로 구성. ( 행과 열의 개수를 알려준다. )
#이미지를 가져왔을 떄 반드시 ndim 과 shape를 확인하자. 

2
(2, 3)


In [26]:
ar=np.arange(1,100,2)
print(ar)
ar=np.linspace(1,100,10)
print(ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


### 특수 함수

In [32]:
ar=np.ones((1,3))
print(ar)

[[1. 1. 1.]]


In [41]:
ar=np.eye(3) # 대각선 방향으로 1을 채운 행렬
print(ar) # 3*3 행렬

ar=np.eye(3,k=1) # 대각선 방향으로 1을 채운 행렬
print(ar) # 3*3 행렬
print("--------------")



ar=np.identity(3)
print(ar)

print(np.diag(ar))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
--------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [51]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(np.diag(ar,k=-1)) # 왼쪽 대각선 방향으로 하나 아래 내려감. 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 8]


In [56]:
ar=np.array([1,2,'3']) # 문자열로 배열 생성
print(ar)

ar=np.array([1,2,'3'],dtype=np.int32) #배열의 자료형 지정. 
print(ar)

ar=np.array([1,2,'3'])
br=ar.astype(np.int32)
print(br) # 자료형 변경. 

['1' '2' '3']
[1 2 3]
[1 2 3]


In [61]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
ar=mat.reshape(-1)
print(ar)
ar[0]=101
print(mat)# 메모리의 주소가 같아 원본도 데이터가 바뀌어버린다. 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [62]:
br=mat.flatten()
print(br)
br[0]=201
print(mat)
print(br)

[101   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]
[201   2   3   4   5   6   7   8   9]


In [63]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0])

[1 2 3]


In [66]:
x=matrix[0][0]
print(x)
print(matrix[0][0])

x=1004
print(x)
print(matrix[0][0])
# [행번호][열번호]\ 이렇게 접근하는 경우는 슬라이싱이라고 하고 
# [행번호,열번호] 가 인덱싱이다. 

1
1
1004
1


In [72]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
# 일반 인덱싱
ar=matrix[0]
br=matrix[0,]
print(ar,br)
ar[0]=100
print(ar)
print(br)
print(matrix)




[1 2 3] [1 2 3]
[100   2   3]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [70]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

# list를 이용한 인덱싱 - fancy 인덱싱
cr=matrix[[0]]

# 범위를 이용하는 형태 - 슬라이싱
dr=matrix[0][:]
print(cr)
print(dr)

[[1 2 3]]
[1 2 3]


### Boolean 값으로 indexing

In [76]:
ar=np.array([10,2,3,46,12,41])
br=np.array([3,65,23,7,1,53])
print(br[ar>=30])

[ 7 53]
